- name: Install i3 packages
  apt:
    state: present
    name:
      - i3
      - i3lock-fancy
      - scrot
      - picom         # Compositor, automatically adds transparency to rofi
      - polybar
      - dunst
      - feh
      - rofi

- name: Enable touchpad settings
  copy:
    dest: /etc/X11/xorg.conf.d/90-touchpad.conf
    src: "{{role_path}}/files/90-touchpad.conf" 
  register: settings

# Necessary to have the touchpad settings activated
- name: Restart display-manager
  service:
    name: display-manager
    state: restarted
  when: settings.changed
