#!/usr/bin/env bash
#
## Usage:
#
# ./bootstrap
#
# This script installs the dependencies necessary to run the playbooks
#
# We use mise (https://mise.jdx.dev/) to manage the python/ansible versions
# declared in mise.toml, then we use ./run to access ansible easily
# The idea is to avoid installing ansible at the user level and keep install
# at the project level

command -v mise >/dev/null 2>&1 || {
    echo "The 'mise' command is not found. Please install it first: https://mise.jdx.dev/installing-mise.html"
    exit 1
}

mise install

cp inventory.sample inventory

# Once ansible is installed install the plugins
# TODO There is probably a better way to do that
mise exec -- ansible-galaxy collection install community.general
mise exec -- ansible-galaxy collection install community.docker
