#!/usr/bin/env bash
#
## Usage:
#
# ./bootstrap
#
# This script installs the dependencies necessary to run the playbooks
#
# Install process following this documentation
# https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html

sudo apt install curl

cp inventory.sample inventory

# Python3 should be already installed but not pip
curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
python3 /tmp/get-pip.py --user

# Install ansible with pip
python3 -m pip install --user ansible

# Once ansible is installed install the plugins (not tested on a new setup)
# TODO There is probably a better way to do that
ansible-galaxy collection install community.general
ansible-galaxy collection install community.docker
ansible-galaxy install ypid.wine
