---
- hosts: panda
  become: false
  vars_files:
    - "./vars/config.local"

  roles:
    - role: system/base
      become: true
    - role: system/sudo
      become: true
    - role: system/docker
      become: true
    - role: server/firewall
      become: true
      vars:
        open_ports:
          - 443
          - 2222
    - role: server/traefik
      vars:
        traefik_dashboard_domain: "panda-traefik.statox.fr"
    - role: server/portainer
      vars:
        portainer_ui_domain: "panda-portainer.statox.fr"
    - role: server/transmission
      vars:
        transmission_ui_domain: "transmission.statox.fr"
        transmission_media_domain: "media.statox.fr"
        jellyfin_domain: "jellyfin.statox.fr"
    - role: server/elk
      vars:
        elastic_cluster_domain: "elk.statox.fr"
        kibana_domain: "kibana.statox.fr"
        logstash_domain: "logs.statox.fr"
    - role: server/api-db
    - role: server/glance
      vars:
        glance_domain: "glance.statox.fr"
