---
- hosts: panda
  become: false
  vars_files:
    - "./vars/config.local"

  roles:
    # - role: system/base
    #   become: yes
    # - role: system/sudo
    #   become: yes
    # - role: system/docker
    #   become: yes
    # - role: user/docker-apps # Must happen after system/docker
    #   vars:
    #     apps:
    #       - portainer
    - role: server/traefik
    - role: server/transmission
    - role: server/elk
