---
- name: Setup panda machine
  hosts: panda
  become: false
  vars_files:
    - "./vars/config.local"

  roles:
    - role: system/base
      become: true
    - role: system/sudo
      become: true
    - role: system/docker
      become: true
    - role: server/firewall
      become: true
      vars:
        open_ports:
          - 443
          - 2222 # For media_sftp.statox.fr
          - 2223 # For gitea.statox.fr ssh cloning
          - 51414 # For servarr-transmission P2P
    - role: server/traefik
      vars:
        traefik_dashboard_domain: "panda-traefik.statox.fr"
    - role: server/portainer
      vars:
        portainer_ui_domain: "panda-portainer.statox.fr"
    - role: server/transmission
      vars:
        transmission_ui_domain: "transmission.statox.fr"
        transmission_media_domain: "media.statox.fr"
        jellyfin_domain: "jellyfin.statox.fr"
    - role: server/elk
      vars:
        elastic_cluster_domain: "elk.statox.fr"
        kibana_domain: "kibana.statox.fr"
        logstash_domain: "logs.statox.fr"
    - role: server/api-db
    - role: server/gitea
    - role: server/planka
      vars:
        planka_ui_domain: "kanban.statox.fr"
    - role: server/servarr
      vars:
        prowlarr_ui_domain: "prowlarr.statox.fr"
        sonarr_ui_domain: "sonarr.statox.fr"
        radarr_ui_domain: "radarr.statox.fr"
        servarr_transmission_ui_domain: "servarr-transmission.statox.fr"
        servarr_jellyfin_domain: "servarr-jellyfin.statox.fr"
