---
- name: Setup work machine
  hosts: local
  become: false
  vars_files:
    - "./vars/config.local"

  roles:
    - role: system/sudo
      become: true
    - role: system/base
      become: true
    - role: system/firewall
      become: true
      vars:
        open_ports:
          - 22 # Needed by IT 😕
    - role: system/i3
      become: true
    - role: system/docker
      become: true
    - role: user/base
    - role: user/nodejs
    - role: ui/nerdfonts # Must happen before user/dconf
    - role: user/dconf
    #- role: user/espanso
    - role: user/github # Must happen before dotfiles
    - role: user/dotfiles
    - role: user/nvim
    - role: user/zsh
    - role: user/dev
    - role: user/kubectl
