# IMPORTANT
# This playbook is still a work in progress.
# 06/04/22:
# - The sudo manipulation must be done manually (same action as in system/sudo)
# - A task requires a reboot which has to be done manually
# - Stuff should be passed as parameter to the roles
---
- name: Setup Raspberry machine
  hosts: raspberry
  become: false
  vars_files:
    - "./vars/config.local"

  roles:
    # - role: system/base
    #   become: true
    # - role: system/docker
    #   become: true
    # - role: raspberry/portainer
    - role: raspberry/pihole
