---
- hosts: panda
  become: false
  vars_files:
    - "./vars/config.local"

  roles:
    - role: system/base
      become: yes
    - role: system/sudo
      become: yes
    - role: system/docker
      become: yes
    - role: server/traefik
    - role: server/portainer
      vars:
      portainer_ui_domain: "panda-portainer.statox.fr"
    - role: server/transmission
      vars:
        transmission_ui_domain: "transmission.statox.fr"
        transmission_media_domain: "media.statox.fr"
    - role: server/elk
