---
- hosts: local
  become: false
  vars_files:
    - "./vars/config.local"

  roles:
    - role: system/base
      become: yes
    - role: system/i3
      become: yes
    - role: system/sudo
      become: yes
    - role: system/docker
      become: yes
    - role: system/podman
    - role: system/wine
    - role: user/base
    - role: ui/nerdfonts # Must happen before user/dconf
    - role: user/dconf
    - role: user/github
    - role: user/dotfiles
    - role: user/nvim
    - role: user/zsh
    - role: user/firefox
    - role: user/usql
    - role: dashlane/base
    - role: dashlane/gitlab
    - role: dashlane/terraform
    - role: dashlane/vault
    # TO FIX:
    # - role: dashlane/sdm


# TODO:
# dotfiles
# Remap escape
  # xmodmap -e "keycode 66 = Escape NoSymbol Escape"
  # xmodmap -pke
# Zoom?
# nvm
# aws-cli
# autokey to remap <alt>+hjkl? https://www.statox.fr/notes/keyboard_remap_arrow_keys/
