#!/usr/bin/env bash

# IMPORTANT
# Ansible Ad hoc commands can't gather facts https://stackoverflow.com/a/36493897
# That means that roles using e.g. ansible_env.USER can't be run with this script

if [ "$#" -ne 1 ] && [ "$#" -ne 2 ]; then
    echo "Illegal number of parameters"
    echo "Usage:"
    echo "run-role [-C] <role-name>"
    exit 1
fi

CHECK=false
for i in "$@"; do
    case $i in
        -C|--check)
            CHECK=true
            ;;
        *)
            ROLE="$i"
            ;;
    esac
done

if [ $CHECK = true ]; then
    ansible localhost -m include_role -a name="$ROLE" --check
else
    ansible localhost -m include_role -a name="$ROLE"
fi
