- name: Install espanso deb
  become: yes
  apt:
    deb: https://github.com/federico-terzi/espanso/releases/download/v2.1.8/espanso-debian-x11-amd64.deb

  register: espanso_install

- name: 'Register espanso service'
  shell: |
    espanso service register
    espanso service start
  when: espanso_install.changed == true
