---
- name: Ensure the dotfiles repo exists
  ansible.builtin.git:
    repo: "git@github.com:statox/dotfiles.git"
    dest: $HOME/.dotfiles
    update: false
  register: clone_dotfiles

- name: "[IMPORTANT] Dotfile repository cloned"
  ansible.builtin.debug:
    msg: "The dotfiles repository was cloned. You should run the setup script"
  when: clone_dotfiles.changed
