---

dependencies: []

galaxy_info:

  author: 'Robin Schneider'
  description: 'Setup and manage Wine for running MS Windows programs'
  license: 'AGPL-3.0'
  min_ansible_version: '2.1.3'

  platforms:

    - name: Debian
      versions:
        - wheezy
        - jessie

    - name: Ubuntu
      versions:
        - precise
        - trusty
        - xenial

  galaxy_tags:
    - wine
    - desktop
    - windows
