---
# TODO add tree-sitter installation from https://github.com/tree-sitter/tree-sitter/releases/tag/
# This is a requirement for nvim-treesitter
# DO NOT install from APT

- name: Install neovim
  ansible.builtin.command: "{{ role_path }}/files/install_nvim.sh"
