---
- name: Install podman
  ansible.builtin.apt:
    state: latest
    name:
      - podman
      - podman-compose
  become: true

- name: Pin podman compose provider to podman-compose
  ansible.builtin.ini_file:
    path: /etc/containers/containers.conf
    section: engine
    option: compose_providers
    value: '["podman-compose"]'
    create: true
  become: true

#- name: Install the podman desktop flatpak
#  community.general.flatpak:
#    name:  https://dl.flathub.org/repo/appstream/io.podman_desktop.PodmanDesktop.flatpakref
#    state: present
#    method: user
