- name: Define variables
  set_fact:
    local_docker_path: "{{role_path}}/docker/"
    docker_apps_home: "{{ ansible_env.HOME }}/.docker-apps"

- name: Ensure docker apps directory exists
  file:
    state: directory
    path: "{{ docker_apps_home }}"

- name: Copy docker apps directory
  copy:
    src: "{{ local_docker_path }}"
    dest: "{{ docker_apps_home }}"

- name: Copy templates to remote host
  template:
    src: "{{ item.src }}"
    dest: "{{ docker_apps_home }}/{{ item.path | regex_replace('.j2','') }}"
  with_filetree: "{{ local_docker_path }}"
  when:
    - item.state == 'file'
    - item.path | regex_search('.j2$')

# ansible-galaxy collection install community.docker
- name: Tear down existing services
  community.docker.docker_compose_v2:
    project_src: "{{ docker_apps_home }}"
    files:
      - docker-compose.transmission.yml
      - docker-compose.elasticsearch.yml
      - docker-compose.webserver.yml
    state: absent

- name: Create and start services
  community.docker.docker_compose_v2:
    # build: always # Need to re-enable when editing Dockerfiles
    project_src: "{{ docker_apps_home }}"
    files:
      - docker-compose.transmission.yml
      - docker-compose.elasticsearch.yml
      - docker-compose.webserver.yml
  register: output

- name: Show results
  debug:
    var: output
