networks:
  reverse-proxy:
    external: true

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - TRANSMISSION_WEB_HOME= #optional
      - USER=${TRANSMISSION_USER} #optional
      - PASS=${TRANSMISSION_PASSWORD} #optional
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - ${TRANSMISSION_DATA_DIR}/data:/config
      - ${TRANSMISSION_DATA_DIR}/downloads:/downloads
      - ${TRANSMISSION_DATA_DIR}/watch/folder:/watch
    ports:
      - ${TRANSMISSION_UI_PORT}:9091
      - ${TRANSMISSION_TORRENT_PORT}:51413
      - ${TRANSMISSION_TORRENT_PORT}:51413/udp
    restart: unless-stopped
    networks:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.rule=Host(`transmission.statox.fr`)"
      - "traefik.http.routers.transmission.entrypoints=websecure"
      - "traefik.http.routers.transmission.tls=true"

  transmission-webserver:
    container_name: transmission-webserver
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ${TRANSMISSION_DATA_DIR}/downloads/complete:/www/data
    networks:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission-webserver.rule=Host(`media.statox.fr`)"
      - "traefik.http.routers.transmission-webserver.entrypoints=websecure"
      - "traefik.http.routers.transmission-webserver.tls=true"
