---

- name: Setup and manage Wine for running MS Windows programs
  hosts: [ 'ypid_service_wine' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: ypid.wine
      tags: [ 'role::wine' ]
