version: "3"

services:
    portainer:
        container_name: portainer
        image: portainer/portainer-ce:latest
        ports:
          - '8000:8000'
          - '9443:9443'
        restart: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - $HOME/.portainer_data:/data
          - ./admin_file_password:/tmp/admin_file_password:ro
        command: --admin-password-file /tmp/admin_file_password
