version: "3"

services:
    portainer:
        container_name: portainer
        image: portainer/portainer-ce:2.11.1
        ports:
          - '8000:8000'
          - '9000:9000'
        restart: always
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - $HOME/.portainer_data:/data
