# Nginx is used to expose elasticsearch endpoints so we need to import
# the network created in ELK's docker-compose file
networks:
  elastic:
    external: true

services:
  # nginx used for SSL termination for external apps
  # Note: Cloudflare is configured in encryption mode "strict" (NOT full)
  # Which means that we can have a self signed certicate between cloudflare and
  # the origin (here nginx). So the Dockerfile generates a self signed certificate
  # valid for 10 years to let future me handle renewal if needed
  # https://developers.cloudflare.com/ssl/origin-configuration/ssl-modes
  webserver:
    container_name: nginx
    build: ./nginx/builder/
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ${TRANSMISSION_DATA_DIR}/downloads/complete:/www/data
