services:
  webserver:
    container_name: nginx
    build: ./nginx/builder/
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ${TRANSMISSION_DATA_DIR}/downloads/complete:/www/data
