- name: Install utilities packages
  become: yes
  apt:
    state: latest
    name:
      - jq
      - curl
      - entr
      - fzf
      - libxml2-utils
      - git
      - ldap-utils
      - redis-tools

- name: Install utilities snaps (edge channel)
  become: yes
  community.general.snap:
    channel: edge
    name:
      - miro

- name: Configure npm repository
  lineinfile:
    name: ~/.npmrc
    line: "npm config set @dashlane:registry https://npm.dashlane.com/repository/npm/=true"

- name: Configure npm repo
  lineinfile:
    name: ~/.npmrc
    line: "npm config set always-auth true=true"

- name: '[IMPORTANT] Command to run'
  debug:
    msg: 'npm adduser --registry=https://npm.dashlane.com/repository/npm/ --scope=@dashlane --always-auth'

- name: Remove Zoom routes from vpn
  blockinfile:
    path: /etc/NetworkManager/dispatcher.d/10-update-vpn-route
    create: yes
    marker: "# {mark} ANSIBLE MANAGED BLOCK FROM STATOX SETUP - Zoom"
    block: |
      # Block added to remove Zoom routes from VPN for better performances
      if [ "$2" != "vpn-up" ]; then
              exit 0;
      fi

      nmcli -t  -f ip4.route c show "${CONNECTION_UUID}" | \
         grep "${IP4_GATEWAY}" | \
         awk -F'[,=\t ]+' '{print $2}' | \
         while read ip; do sudo ip route add ${ip} via "${IP4_GATEWAY}"; done
  become: true
