- name: Read current terminal profile
  shell: "dconf list /org/gnome/terminal/legacy/profiles:/ | head -1  | grep . || echo ':11111111-1111-1111-1111-111111111111/'"
  register: term_profile
  changed_when: no

- name: Set dconf values
  include_tasks: dconf.yml
  loop:
    - key: /org/gnome/terminal/legacy/default-show-menubar
      value: "false"
    - key: /org/gnome/terminal/legacy/theme-variant
      value: "'dark'" # The single quotes are needed otherwise dconf returns an error
    - key: /org/gnome/terminal/legacy/profiles:/{{term_profile.stdout}}font
      value: "'AurulentSansMono Nerd Font 12'"
  loop_control:
    loop_var: item
    index_var: index
