# TODO
# This playbook needs a fix
# The profile is not read properly the first time it runs
# it must be set manually with the output of the dconf comand.
- name: Read current terminal profile
  shell: "dconf list /org/gnome/terminal/legacy/profiles:/ | head -1  | grep . || echo ':b1dcc9dd-5262-4d8d-a863-c897e6d979b9/'"
  register: term_profile
  changed_when: no

- name: Set dconf values
  include_tasks: dconf.yml
  loop:
    - key: /org/gnome/terminal/legacy/default-show-menubar
      value: "false"
    - key: /org/gnome/terminal/legacy/theme-variant
      value: "'dark'" # The single quotes are needed otherwise dconf returns an error
    - key: /org/gnome/terminal/legacy/profiles:/{{term_profile.stdout}}font
      value: "'AurulentSansMono Nerd Font 12'"
    - key: /org/gnome/terminal/legacy/profiles:/{{term_profile.stdout}}scrollbar-policy
      value: "'never'"
  loop_control:
    loop_var: item
    index_var: index
