---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker

# ypid.wine default variables [[[
# ===============================

# .. contents:: Sections
#    :local:
#
# .. include:: includes/all.rst


# Packages and installation [[[
# -----------------------------

# .. envvar:: wine__base_packages [[[
#
# List of base packages to install.
wine__base_packages:
  - '{{ [ "libwine-print:i386" ] if (ansible_distribution == "Debian") else [] }}'
  - [ "wine32", "winetricks"]

  ## Needed for wine. https://www.winehq.org/docs/wineusr-guide/misc-things-to-configure#AEN942
  - 'cups-bsd'

  ## Needed for printing. https://forums.linuxmint.com/viewtopic.php?t=168952
  - 'libcups2:i386'

  ## Does not have wine-gecko?
  # - 'wine-development'

                                                                   # ]]]
# .. envvar:: wine__architecture_i386_enabled [[[
#
# List of base packages to install.
wine__architecture_i386_enabled: True

                                                                   # ]]]
# .. envvar:: wine__deploy_state [[[
#
# What is the desired state which this role should achieve? Possible options:
#
# ``present``
#   Default. Ensure that Wine is installed and configured as requested.
#
# ``absent``
#   Ensure that Wine is uninstalled and it's configuration is removed.
#
wine__deploy_state: 'present'
                                                                   # ]]]
                                                                   # ]]]
                                                                   # ]]]
