# IMPORTANT:
# This role is used to install docker containers. Using a shell command
# is not the most reliable way (there is a community role to do that) but
# I want to keep this setup simple and galaxy requires some configuration.
#
# HOW TO USE:
# in the files/ directory of this role add a new directory [app_name]/
# in [app_name]/ create the docker-compose.yml of the new app to install
# in the items of this role add [app_name]/

- name: Define variables
  set_fact:
    docker_apps_home: "{{ ansible_env.HOME }}/.docker-apps"

- name: Ensure docker apps directory exists
  file:
    state: directory
    path: "{{ docker_apps_home }}"

- name: Copy docker apps directories
  include_tasks: copy-directory.yml
  loop: "{{ apps }}"
  loop_control:
    loop_var: app_name

- name: Run docker apps containers
  include_tasks: run-app-containers.yml
  loop: "{{ apps }}"
  loop_control:
    loop_var: app_name
