---
- name: Fail if prowlarr_ui_domain is undefined
  ansible.builtin.fail:
    msg: "Variable '{{ prowlarr_ui_domain }}' is not defined"
  when: prowlarr_ui_domain is undefined

- name: Fail if sonarr_ui_domain is undefined
  ansible.builtin.fail:
    msg: "Variable '{{ sonarr_ui_domain }}' is not defined"
  when: sonarr_ui_domain is undefined

- name: Fail if radarr_ui_domain is undefined
  ansible.builtin.fail:
    msg: "Variable '{{ radarr_ui_domain }}' is not defined"
  when: radarr_ui_domain is undefined

- name: Fail if servarr_transmission_ui_domain is undefined
  ansible.builtin.fail:
    msg: "Variable '{{ servarr_transmission_ui_domain }}' is not defined"
  when: servarr_transmission_ui_domain is undefined

- name: Fail if servarr_jellyfin_domain is undefined
  ansible.builtin.fail:
    msg: "Variable '{{ servarr_jellyfin_domain }}' is not defined"
  when: servarr_jellyfin_domain is undefined

- name: Fail if bazarr_ui_domain is undefined
  ansible.builtin.fail:
    msg: "Variable '{{ bazarr_ui_domain }}' is not defined"
  when: bazarr_ui_domain is undefined

- name: Create servarr data and config directories
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "1000"
    group: "1000"
    mode: "0755"
  loop:
    - /home/servarr/data/torrents/incomplete
    - /home/servarr/data/torrents/complete/movies
    - /home/servarr/data/torrents/complete/tv
    - /home/servarr/data/library/movies
    - /home/servarr/data/library/tv
    - /home/servarr/config/transmission
    - /home/servarr/config/prowlarr
    - /home/servarr/config/sonarr
    - /home/servarr/config/radarr
    - /home/servarr/config/jellyfin
    - /home/servarr/config/bazarr
    - /home/servarr/cache/jellyfin

- name: Install servarr docker app
  ansible.builtin.import_tasks: ../../docker_compose_setup/main.yml
  vars:
    app_name: servarr
    local_docker_path: "{{ role_path }}/files/docker/"
